config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get '/search' => 'search#index'
  get '/download' => 'search#download'
  get '/plan_download' => 'search#plan_download'

  resources :licenses do
    resources :taxes, only: [:new, :create, :destroy]
    resources :statements, except: [:index, :show]
    resource :business_plan, only: [:show, :create, :update]
  end

  resources :taxes, only: [:index]
  resources :companies, only: [:index, :show]

  # scope :api do
  #   resources :licenses do
  #     resources :statements
  #   end
  # end

  # match '*path', to: 'home#index', via: :all
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = License.ransack(params[:q])
    @licenses = @q.result(distinct: true)
      .includes(:business_plan)
      .order(:category_id, :created_at)
      .page(params[:page]).per(params[:per_page])
  end

  def download
    respond_to do |format|
      format.xls do
        @licenses = License.ransack(params[:q])
          .result(distinct: true)
          .includes(:business_plan)
          .unique_by_latest_expires_date
          .order(:category_id, :created_at)

        path = Licenses::CSVService.new(@licenses).to_csv
        data = File.read(path)
        send_data data, filename: 'អាជ្ញាបណ្ណ.xls'
        FileUtils.rm path
      end
    end
  end

  def plan_download
    respond_to do |format|
      format.xls do
        @licenses = License.ransack(params[:q])
          .result(distinct: true)
          .includes(:business_plan)
          .unique_by_latest_expires_date
          .order(:category_id, :created_at)

        path = Plans::CSVService.new(@licenses).to_csv
        data = File.read(path)
        send_data data, filename: 'ស្ថិតិផែនការផលិតកម្ម.xls'
        FileUtils.rm path
      end
    end
  end

  # def tax_download
  #   respond_to do |format|
  #     format.html { @q = Tax.ransack(params[:q]) }
  #     format.xlsx do
  #       @taxes = Tax.ransack(params[:q]).result.order(:year, :month)

  #       path = Taxes::CSVService.new(@taxes).to_csv
  #       data = File.read(path)
  #       send_data data, filename: 'តារាងតាមដានបរិមាណនិងការបង់សួយសារ.xls'
  #       FileUtils.rm path
  #     end
  #   end
  # end
end

app/views/search/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title text-center mb-4"><%= t('search_license') %></h3><hr />

        <div class="row mb-4">
          <div class="col-12">
            <%= search_form_for @q, url: search_path, class: 'form' do |f| %>
              <div class="form-row">
                <div class="col-4">
                  <div class="form-group">
                    <%= f.label :number %>
                    <%= f.search_field :number_cont, class: 'form-control' %>
                  </div>
                </div>
                <div class="col-4">
                  <div class="form-group">
                    <%= f.label :valid_from %>
                    <%= f.select :valid_year_from, year_options, { include_blank: t('select_option') }, class: 'form-control' %>
                  </div>
                </div>
                <div class="col-4">
                  <div class="form-group">
                    <%= f.label :valid_to %>
                    <%= f.select :valid_year_to, year_options, { include_blank: t('select_option') }, class: 'form-control' %>
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-4">
                  <div class="form-group">
                    <%= f.label :province %>
                    <%= f.select :province_eq, License.selectable_search_province, { include_blank: t('select_option') }, { class: 'form-control' } %>
                  </div>
                </div>
                <div class="col-4">
                  <div class="form-group">
                    <%= f.label :category, t('activerecord.attributes.license.category') %>
                    <%= f.select :category_id_eq, Category.all.map { |c| [c.name, c.id] }, { include_blank: t('select_option') }, { class: 'form-control' } %>
                  </div>
                </div>
                <div class="col-4">
                  <div class="form-group">
                    <%= f.label :status %>
                    <%= f.select :status_eq, License.selectable_search_status, { include_blank: t('select_option') }, { class: 'form-control' } %>
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-12 text-right">
                  <div class="form-group">
                    <label></label>
                    <%= f.submit t('search_license'), class: 'btn btn-primary' %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="clearfix mb-4">
          <%= link_to t('download_csv'), request.url.sub('search', 'download.xls'), class: 'float-right btn btn-white' %>
          <%= link_to t('download_plan_csv'), request.url.sub('search', 'plan_download.xls'), class: 'float-right btn btn-white mr-2' %>
        </div>
        <%= render 'licenses/table', licenses: @licenses %>
      </div>
    </div>
  </div>
</div>

app/views/search/tax_download.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title text-center mb-4"><%= t('download_tax_csv') %></h1><hr />

        <div class="row mb-4">
          <div class="col-12">
            <%= search_form_for @q, url: tax_download_path(format: :xlsx), class: 'form' do |f| %>
              <div class="form-group">
                <%= f.select :year_eq, year_options, { include_blank: t('select_option'), selected: Date.current.year }, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.submit t('download_tax_csv'), class: 'form-control btn btn-primary btn-lg' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.form').on('submit', function() {
    var self = this;
    setTimeout(function() {
      $(self).find('input[type=submit]').attr('disabled', false);
    }, 500)
  });
</script>