config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get '/search' => 'search#index'
  get '/download' => 'search#download'
  get '/plan_download' => 'search#plan_download'

  resources :licenses do
    resources :taxes, only: [:new, :create, :destroy]
    resources :statements, except: [:index, :show]
    resource :business_plan, only: [:show, :create, :update]
  end

  resources :taxes, only: [:index]
  resources :companies, only: [:index, :show]

  # scope :api do
  #   resources :licenses do
  #     resources :statements
  #   end
  # end

  # match '*path', to: 'home#index', via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="logo text-center">
      <%= image_tag 'logo.png', class: 'd-block w-100' %>
    </div>
    <div class="card">
      <div class="card-body">
        <h1 class="card-title text-center mb-4"><%= t('menu') %></h1>
        <hr />
        <div class="row mt-4 mb-4">
          <div class="col-12 text-center">
            <%= link_to t('create_license'), new_license_path, class: 'w-100 btn btn-primary btn-lg' %>
          </div>
        </div>
        <div class="row mt-4 mb-4">
          <div class="col-12 text-center">
            <%= link_to t('licenses_index'), licenses_path, class: 'w-100 btn btn-primary btn-lg' %>
          </div>
        </div>
        <div class="row mt-4 mb-4">
          <div class="col-12 text-center">
            <%= link_to t('search_license'), search_path, class: 'w-100 btn btn-primary btn-lg' %>
          </div>
        </div>
        <div class="row mt-4 mb-4">
          <div class="col-12 text-center">
            <%= link_to t('tax_title'), taxes_path, class: 'w-100 btn btn-primary btn-lg' %>
          </div>
        </div>
        <div class="row mt-4 mb-4">
          <div class="col-12 text-center">
            <%= link_to t('company_history'), companies_path, class: 'w-100 btn btn-primary btn-lg' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>